### ISSUE TITLE
ifl-2021.pptx link in Readme is incorrect

### ISSUE THREAD

**Issue by waivio** [sweirich/lambda-n-ways#1]
The "ifl-2021.pptx" link in the README.md is:
https://github.com/sweirich/lambda-n-ways/blob/main/ifl-2021.pptx

I think it should be:
https://github.com/sweirich/lambda-n-ways/blob/main/doc/ifl-2021.pptx

**Comment by sweirich** [comment]
Thanks! I've updated.
